version: 2

builds:
  - binary: highlife
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz

brews:
  - repository:
      owner: semgrep
      name: highlife
    directory: Formula
    homepage: https://github.com/semgrep/highlife
    description: Keep Homebrew packages installed and up-to-date from remote Brewfiles.
    license: Apache-2.0
