# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Highlife < Formula
  desc "Keep Homebrew packages installed and up-to-date from remote Brewfiles."
  homepage "https://github.com/semgrep/highlife"
  version "0.9.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/semgrep/highlife/releases/download/v0.9.3/highlife_0.9.3_darwin_amd64.tar.gz"
      sha256 "6f1fed919ddc003dbc26548da9423a0326628b11a245a1968da584ebf8d04e21"

      def install
        bin.install "highlife"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/semgrep/highlife/releases/download/v0.9.3/highlife_0.9.3_darwin_arm64.tar.gz"
      sha256 "3ba6a8b40eb4c1c5472832ebe5b483bb2a768c1bda5764f51db5e5d4f4642365"

      def install
        bin.install "highlife"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/semgrep/highlife/releases/download/v0.9.3/highlife_0.9.3_linux_amd64.tar.gz"
      sha256 "eca1c1fa264c667818f276dd46c6b95900b978559da6c7969d097e1e2d26032c"
      def install
        bin.install "highlife"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/semgrep/highlife/releases/download/v0.9.3/highlife_0.9.3_linux_arm64.tar.gz"
      sha256 "92ba6bb77987d38e0b70711c802607f6e65f8559ce812e0deb55f8be2389316a"
      def install
        bin.install "highlife"
      end
    end
  end
end
