# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Highlife < Formula
  desc "Keep Homebrew packages installed and up-to-date from remote Brewfiles."
  homepage "https://github.com/semgrep/highlife"
  version "0.9.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/semgrep/highlife/releases/download/v0.9.1/highlife_0.9.1_darwin_amd64.tar.gz"
      sha256 "5e3aec1df1a6f766132c99822648f89c5625d8a57f32407988a510aba2cbbe00"

      def install
        bin.install "highlife"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/semgrep/highlife/releases/download/v0.9.1/highlife_0.9.1_darwin_arm64.tar.gz"
      sha256 "7f2e08216219bc34ed1bc597ee1fa07373ac7a258fef4ee3b6d35aa097372e18"

      def install
        bin.install "highlife"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/semgrep/highlife/releases/download/v0.9.1/highlife_0.9.1_linux_amd64.tar.gz"
      sha256 "90c96f735d48f075072c4079d62b5de6f46a63e12d6ed84ecfbd0ee5306c7294"
      def install
        bin.install "highlife"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/semgrep/highlife/releases/download/v0.9.1/highlife_0.9.1_linux_arm64.tar.gz"
      sha256 "0cac1d759054b6194f78d47102a8bef78eaad13d4c2d384c8ea89dab9cbead17"
      def install
        bin.install "highlife"
      end
    end
  end
end
