# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Highlife < Formula
  desc "Keep Homebrew packages installed and up-to-date from remote Brewfiles."
  homepage "https://github.com/semgrep/highlife"
  version "0.9.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/semgrep/highlife/releases/download/v0.9.5/highlife_0.9.5_darwin_amd64.tar.gz"
      sha256 "73d390b630662950387acb5bdf2894a260c724dbcac5dab2a54db495469da963"

      def install
        bin.install "highlife"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/semgrep/highlife/releases/download/v0.9.5/highlife_0.9.5_darwin_arm64.tar.gz"
      sha256 "dd6ea171fdb4c61a0ed2137c5d1cc4a9147961b3bb3f1b73ef6f75255a886920"

      def install
        bin.install "highlife"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/semgrep/highlife/releases/download/v0.9.5/highlife_0.9.5_linux_amd64.tar.gz"
      sha256 "6d1efdf5a501dfcfbfe004c4632ca38d72b6c5502d463ee830ba429389c936e8"
      def install
        bin.install "highlife"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/semgrep/highlife/releases/download/v0.9.5/highlife_0.9.5_linux_arm64.tar.gz"
      sha256 "6211b2da318457cadc771950bca94d568bd79d0b181d3849c5dc7b4b3aca85af"
      def install
        bin.install "highlife"
      end
    end
  end
end
